CREATE DATABASE iconnectsampleapplab CHARACTER SET utf8;

DROP TABLE IF EXISTS `TBL_WARD`;
CREATE TABLE `TBL_WARD` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `WARD_REFERENCE_ID` VARCHAR(7) DEFAULT NULL,
  `WARD_NAME` VARCHAR(10) DEFAULT NULL,
  `WARD_CLASS_TYPE` VARCHAR(20) DEFAULT NULL,
  `WARD_LOCATION` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_ID` (`WARD_REFERENCE_ID`),
  UNIQUE KEY `UNIQUE_WARD` (`WARD_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `TBL_BED`;
CREATE TABLE `TBL_BED` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `BED_REFERENCE_ID` VARCHAR(6) DEFAULT NULL,
  `BED_NAME` VARCHAR(17) DEFAULT NULL,
  `WARD_ID` BIGINT(20) DEFAULT NULL,
  `WARD_ALLOCATION_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE `TBL_BED`
ADD FOREIGN KEY (WARD_ID) REFERENCES TBL_WARD(ID);


